version: '3'
services:
  node:
    image: 'node:lts'
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ${PWD}:/var/www/app
    working_dir: /var/www/app
    links:
      - mysql
    command: bash -c "rm -rf dist && yarn run start:dev"
  mysql:
    image: 'mysql:8'
    volumes:
      - 'db-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
volumes:
  db-data:
    driver: local